<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <PropertyGroup>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <WarningsAsErrors>nullable</WarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Peyman Mohammadi</Authors>
        <PackageId>MovieFileLibrary</PackageId>
        <Copyright>© 2022 Peyman Mohammadi</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>movie; series; detect; file</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <RepositoryUrl>https://github.com/moviecollection/movie-file-library</RepositoryUrl>
        <PackageProjectUrl>https://github.com/moviecollection/movie-file-library</PackageProjectUrl>
        <Description>A library for extracting basic information from a movie file name.</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
